spring.datasource.url=jdbc:postgresql://localhost:5433/loja_virtual_mentoria
spring.datasource.name=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.platform=postgres


